module.exports = {
  apps: [
    {
      name: 'precivox-backend',
      script: 'npx',
      args: 'tsx src/server.ts',
      cwd: '/root',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'production',
        PORT: 3001,
      },
      error_file: '/var/log/precivox-backend-error.log',
      out_file: '/var/log/precivox-backend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
    {
      name: 'precivox-frontend',
      script: 'npm',
      args: 'start',
      cwd: '/root',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
      },
      error_file: '/var/log/precivox-frontend-error.log',
      out_file: '/var/log/precivox-frontend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
    {
      name: 'precivox-ai-scheduler',
      script: 'npx',
      args: 'tsx core/ai/run-scheduler.ts',
      cwd: '/root',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      env: {
        NODE_ENV: 'production',
      },
      error_file: '/var/log/precivox-scheduler-error.log',
      out_file: '/var/log/precivox-scheduler-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      cron_restart: '0 0 * * *', // Reiniciar diariamente à meia-noite
    },
  ],
};
