/**
 * Textos da interface em linguagem simples — jornada do cliente Precivox.
 */

export const UX = {
  busca: {
    titulo: 'Buscar produtos',
    subtitulo: 'Encontre e compare preços nos mercados perto de você',
    placeholder: 'O que você procura?',
    filtros: 'Filtrar e ordenar',
    maisOpcoes: 'Mais opções',
    lista: 'Minha lista',
    recolherLista: 'Recolher lista',
    compararPrecos: 'Comparar preços',
    verLista: 'Ver em lista',
    ordenar: 'Ordenar por',
    ordenacao: {
      hibrido: 'Mais relevantes',
      preco_asc: 'Menor preço',
      nome: 'Nome (A–Z)',
    },
    carregando: 'Buscando produtos…',
    semResultado: 'Nenhum resultado',
    semResultadoDica: 'Tente outro nome ou remova alguns filtros.',
    limparFiltros: 'Limpar filtros',
    resultados: (n: number, total?: number, comparativo?: boolean) => {
      const tipo = comparativo ? 'ofertas' : 'produtos';
      if (total && total > n) return `${n.toLocaleString('pt-BR')} de ${total.toLocaleString('pt-BR')} ${tipo}`;
      return `${n.toLocaleString('pt-BR')} ${tipo}`;
    },
    erroTitulo: 'Algo deu errado',
    erroGenerico: 'Estamos com um problema temporário. Tente de novo em instantes.',
    tentarNovamente: 'Tentar de novo',
    carregarMais: 'Carregar mais',
  },
  lista: {
    titulo: 'Lista inteligente',
    subtituloVazia: 'Adicione produtos pela busca',
    itens: (n: number) => (n === 1 ? '1 item' : `${n} itens`),
    continuarComprando: 'Continuar comprando',
    finalizarCompras: 'Ir às compras',
    finalizarComprasDescricao: 'Use a lista no corredor do mercado',
    irCorredorVazio: 'Adicione produtos para ir às compras',
    esvaziar: 'Esvaziar lista',
    renomear: 'Renomear lista',
    trocarLista: 'Trocar lista',
    verTodas: 'Ver todas as listas',
    remover: 'Remover',
    desfazer: 'Desfazer',
    itemRemovido: 'Item removido da lista',
    confirmarEsvaziar: 'Tem certeza que deseja esvaziar a lista?',
    rotaIa: 'Rota e dicas',
    analiseIa: 'Análise da sua lista',
    analiseIaCarregando: 'Analisando sua lista…',
    sugestoesIa: 'Sugestões para completar sua cesta',
  },
  catalogo: {
    titulo: 'Mercados disponíveis',
    ofertasRegiao: 'Ofertas na região',
    parceiroRegiao: 'Parceiro da região',
    promocaoDirecionada: 'Promoção especial',
  },
  produto: {
    adicionar: 'Adicionar à lista',
    adicionando: 'Adicionando…',
    adicionado: 'Adicionado!',
    verDetalhes: 'Ver detalhes',
    ocultarDetalhes: 'Ocultar detalhes',
    promocao: 'Promoção',
    menorPreco: 'Menor preço',
  },
  nav: {
    inicio: 'Início',
    buscar: 'Buscar',
    listas: 'Listas',
    despensa: 'Despensa',
    perfil: 'Perfil',
    /** Shell AI-Native (Fase 1) */
    casa: 'Casa',
    compra: 'Compra',
    scanner: 'Escanear',
    mais: 'Mais',
  },
  casaAgora: {
    titulo: 'O que a casa precisa agora?',
    subtitulo: 'Revise a compra sugerida ou diga o que falta.',
    ctaPrimario: 'Revisar compra sugerida',
    ctaSecundarioBusca: 'Buscar produto',
    hubPlaceholder: 'O que a casa precisa?',
    hubDica: 'Diga o que precisa ou use um atalho — abrimos a tela certa.',
    membros: 'Minha Casa',
    cicloSemPrevisao: 'Quando você confirmar compras, mostramos a próxima previsão aqui.',
  },
  compra: {
    titulo: 'Sua compra',
    subtituloVazia: 'Monte a compra sugerida em um toque — ou busque um produto.',
    irBuscar: 'Buscar produtos',
    verListas: 'Todas as listas',
    montarSemana: 'Montar compra da semana',
    listaVazia: 'Criar lista vazia',
  },
  despensa: {
    titulo: 'Despensa',
    subtitulo: 'O que costuma acabar em casa — sem inventar estoque.',
    incluir: 'Incluir na compra',
    incluindo: 'Incluindo…',
    incluido: 'Incluído na compra',
    verCompra: 'Ver compra',
    adicionarManual: 'Adicionar manual',
    vazio: 'Nenhum item ainda. Adicione o que costuma faltar ou compre pelo app para aprendermos o ritmo.',
    escolherMercadoParaCompra: 'Onde quer comprar este item?',
    escolherMercadoDica: 'A despensa é da casa. O mercado só serve para achar preço agora.',
    cancelar: 'Cancelar',
    cicloDias: 'Ciclo (dias)',
    semEstoque: 'Não há oferta deste item neste mercado agora. Busque pelo nome.',
  },
  mais: {
    titulo: 'Mais',
    subtitulo: 'Conta, preferências e atalhos',
    conta: 'Conta e preferências',
    perfilPrefs: 'Preferências da casa',
    familia: 'Minha Casa (membros)',
    mercadoVivo: 'Modo corredor',
    busca: 'Buscar produtos',
    listas: 'Todas as listas',
    scan: 'Escanear etiqueta',
    secaoPrefs: 'Preferências',
    secaoAtalhos: 'Atalhos',
  },
  perfil: {
    titulo: 'Preferências da casa',
    subtitulo: 'Ajuste como o app trata suas compras. Quase nunca precisa mexer aqui.',
    eixosTitulo: 'Seu jeito de comprar',
    eixosDica: 'Arraste só se quiser corrigir. O restante o app aprende sozinho com o uso.',
    salvar: 'Salvar preferências',
    intentTitulo: 'Próxima compra (estimativa)',
    porQue: 'Por que sugerimos assim?',
    ajustarPrefs: 'Ajustar preferências',
  },
  hub: {
    /** Copy sem jargão de IA — princípio-mestre */
    placeholder: 'O que a casa precisa?',
    foto: 'Foto da etiqueta ou produto',
    fotoLendo: 'Lendo a foto…',
    fotoErro: 'Não deu para ler a foto. Tente de novo ou digite o que precisa.',
    chips: {
      semana: 'Compra da semana',
      adicionar: 'Adicionar itens',
      mercado: 'Estou no mercado',
      escanear: 'Escanear',
    },
  },
  geral: {
    fechar: 'Fechar',
    salvar: 'Salvar',
    cancelar: 'Cancelar',
    limpar: 'Limpar',
    mais: 'Mais',
  },
} as const;

export type OrdenacaoBusca = 'hibrido' | 'preco_asc' | 'nome';
